volumes:
  maven-repo:
  
services:
  oots-evidence-finder:
    volumes:
      - maven-repo:/root/.m2
    container_name: "oots-evidence-finder"
    build:
      context: ../oots-evidence-finder
      dockerfile: ../oots-evidence-finder/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - COMMON_SERVICES_EB_URL=${COMMON_SERVICES_EB_URL}
      - COMMON_SERVICES_DSD_URL=${COMMON_SERVICES_DSD_URL}
      
      
