version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - COMMON_SERVICES_URL=https://projectathon.oots-common-services.eu
