//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 05:27:25 PM CEST 
//


package sk.mirri.ootsevidencefinder.wsplugin.sdg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataServiceEvidenceTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataServiceEvidenceTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://data.europa.eu/p4s}Identifier"/>
 *         &lt;element name="EvidenceTypeClassification" type="{http://data.europa.eu/p4s}CodeType"/>
 *         &lt;element ref="{http://data.europa.eu/p4s}Title" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://data.europa.eu/p4s}Description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DistributedAs" type="{http://data.europa.eu/p4s}EvidenceTypeDistributionType" maxOccurs="unbounded"/>
 *         &lt;element name="AccessService" type="{http://data.europa.eu/p4s}DataServiceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AuthenticationLevelOfAssurance" type="{http://data.europa.eu/p4s}CodeType" minOccurs="0"/>
 *         &lt;element ref="{http://data.europa.eu/p4s}EvidenceProviderJurisdictionDetermination" minOccurs="0"/>
 *         &lt;element ref="{http://data.europa.eu/p4s}EvidenceProviderClassification" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataServiceEvidenceTypeType", propOrder = {
    "identifier",
    "evidenceTypeClassification",
    "title",
    "description",
    "distributedAs",
    "accessService",
    "authenticationLevelOfAssurance",
    "evidenceProviderJurisdictionDetermination",
    "evidenceProviderClassification"
})
public class DataServiceEvidenceTypeType {

    @XmlElement(name = "Identifier", required = true)
    protected IdentifierType identifier;
    @XmlElement(name = "EvidenceTypeClassification", required = true)
    protected CodeType evidenceTypeClassification;
    @XmlElement(name = "Title", required = true)
    protected List<MultilingualStringType> title;
    @XmlElement(name = "Description")
    protected List<MultilingualStringType> description;
    @XmlElement(name = "DistributedAs", required = true)
    protected List<EvidenceTypeDistributionType> distributedAs;
    @XmlElement(name = "AccessService")
    protected List<DataServiceType> accessService;
    @XmlElement(name = "AuthenticationLevelOfAssurance")
    protected CodeType authenticationLevelOfAssurance;
    @XmlElement(name = "EvidenceProviderJurisdictionDetermination")
    protected JurisdictionDeterminationType evidenceProviderJurisdictionDetermination;
    @XmlElement(name = "EvidenceProviderClassification")
    protected List<InformationConceptType> evidenceProviderClassification;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the evidenceTypeClassification property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getEvidenceTypeClassification() {
        return evidenceTypeClassification;
    }

    /**
     * Sets the value of the evidenceTypeClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setEvidenceTypeClassification(CodeType value) {
        this.evidenceTypeClassification = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultilingualStringType }
     * 
     * 
     */
    public List<MultilingualStringType> getTitle() {
        if (title == null) {
            title = new ArrayList<MultilingualStringType>();
        }
        return this.title;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultilingualStringType }
     * 
     * 
     */
    public List<MultilingualStringType> getDescription() {
        if (description == null) {
            description = new ArrayList<MultilingualStringType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the distributedAs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distributedAs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistributedAs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvidenceTypeDistributionType }
     * 
     * 
     */
    public List<EvidenceTypeDistributionType> getDistributedAs() {
        if (distributedAs == null) {
            distributedAs = new ArrayList<EvidenceTypeDistributionType>();
        }
        return this.distributedAs;
    }

    /**
     * Gets the value of the accessService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataServiceType }
     * 
     * 
     */
    public List<DataServiceType> getAccessService() {
        if (accessService == null) {
            accessService = new ArrayList<DataServiceType>();
        }
        return this.accessService;
    }

    /**
     * Gets the value of the authenticationLevelOfAssurance property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getAuthenticationLevelOfAssurance() {
        return authenticationLevelOfAssurance;
    }

    /**
     * Sets the value of the authenticationLevelOfAssurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setAuthenticationLevelOfAssurance(CodeType value) {
        this.authenticationLevelOfAssurance = value;
    }

    /**
     * Gets the value of the evidenceProviderJurisdictionDetermination property.
     * 
     * @return
     *     possible object is
     *     {@link JurisdictionDeterminationType }
     *     
     */
    public JurisdictionDeterminationType getEvidenceProviderJurisdictionDetermination() {
        return evidenceProviderJurisdictionDetermination;
    }

    /**
     * Sets the value of the evidenceProviderJurisdictionDetermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link JurisdictionDeterminationType }
     *     
     */
    public void setEvidenceProviderJurisdictionDetermination(JurisdictionDeterminationType value) {
        this.evidenceProviderJurisdictionDetermination = value;
    }

    /**
     * Gets the value of the evidenceProviderClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evidenceProviderClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidenceProviderClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InformationConceptType }
     * 
     * 
     */
    public List<InformationConceptType> getEvidenceProviderClassification() {
        if (evidenceProviderClassification == null) {
            evidenceProviderClassification = new ArrayList<InformationConceptType>();
        }
        return this.evidenceProviderClassification;
    }

}
