//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 05:27:25 PM CEST 
//


package sk.mirri.ootsevidencefinder.wsplugin.sdg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for EvidenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvidenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://data.europa.eu/p4s}Identifier"/>
 *         &lt;element name="IsAbout">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="NaturalPerson" type="{http://data.europa.eu/p4s}PersonType"/>
 *                   &lt;element name="LegalPerson" type="{http://data.europa.eu/p4s}LegalPersonType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="IssuingAuthority" type="{http://data.europa.eu/p4s}AgentType"/>
 *         &lt;element name="IsConformantTo" type="{http://data.europa.eu/p4s}EvidenceTypeType"/>
 *         &lt;element name="IssuingDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Distribution" type="{http://data.europa.eu/p4s}DistributionType"/>
 *         &lt;element name="ValidityPeriod" type="{http://data.europa.eu/p4s}PeriodType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvidenceType", propOrder = {
    "identifier",
    "isAbout",
    "issuingAuthority",
    "isConformantTo",
    "issuingDate",
    "distribution",
    "validityPeriod"
})
public class EvidenceType {

    @XmlElement(name = "Identifier", required = true)
    protected IdentifierType identifier;
    @XmlElement(name = "IsAbout", required = true)
    protected EvidenceType.IsAbout isAbout;
    @XmlElement(name = "IssuingAuthority", required = true)
    protected AgentType issuingAuthority;
    @XmlElement(name = "IsConformantTo", required = true)
    protected EvidenceTypeType isConformantTo;
    @XmlElement(name = "IssuingDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issuingDate;
    @XmlElement(name = "Distribution", required = true)
    protected DistributionType distribution;
    @XmlElement(name = "ValidityPeriod")
    protected PeriodType validityPeriod;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setIdentifier(IdentifierType value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the isAbout property.
     * 
     * @return
     *     possible object is
     *     {@link EvidenceType.IsAbout }
     *     
     */
    public EvidenceType.IsAbout getIsAbout() {
        return isAbout;
    }

    /**
     * Sets the value of the isAbout property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvidenceType.IsAbout }
     *     
     */
    public void setIsAbout(EvidenceType.IsAbout value) {
        this.isAbout = value;
    }

    /**
     * Gets the value of the issuingAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link AgentType }
     *     
     */
    public AgentType getIssuingAuthority() {
        return issuingAuthority;
    }

    /**
     * Sets the value of the issuingAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgentType }
     *     
     */
    public void setIssuingAuthority(AgentType value) {
        this.issuingAuthority = value;
    }

    /**
     * Gets the value of the isConformantTo property.
     * 
     * @return
     *     possible object is
     *     {@link EvidenceTypeType }
     *     
     */
    public EvidenceTypeType getIsConformantTo() {
        return isConformantTo;
    }

    /**
     * Sets the value of the isConformantTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EvidenceTypeType }
     *     
     */
    public void setIsConformantTo(EvidenceTypeType value) {
        this.isConformantTo = value;
    }

    /**
     * Gets the value of the issuingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssuingDate() {
        return issuingDate;
    }

    /**
     * Sets the value of the issuingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssuingDate(XMLGregorianCalendar value) {
        this.issuingDate = value;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * @return
     *     possible object is
     *     {@link DistributionType }
     *     
     */
    public DistributionType getDistribution() {
        return distribution;
    }

    /**
     * Sets the value of the distribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionType }
     *     
     */
    public void setDistribution(DistributionType value) {
        this.distribution = value;
    }

    /**
     * Gets the value of the validityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    public PeriodType getValidityPeriod() {
        return validityPeriod;
    }

    /**
     * Sets the value of the validityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setValidityPeriod(PeriodType value) {
        this.validityPeriod = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="NaturalPerson" type="{http://data.europa.eu/p4s}PersonType"/>
     *         &lt;element name="LegalPerson" type="{http://data.europa.eu/p4s}LegalPersonType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naturalPerson",
        "legalPerson"
    })
    public static class IsAbout {

        @XmlElement(name = "NaturalPerson")
        protected PersonType naturalPerson;
        @XmlElement(name = "LegalPerson")
        protected LegalPersonType legalPerson;

        /**
         * Gets the value of the naturalPerson property.
         * 
         * @return
         *     possible object is
         *     {@link PersonType }
         *     
         */
        public PersonType getNaturalPerson() {
            return naturalPerson;
        }

        /**
         * Sets the value of the naturalPerson property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonType }
         *     
         */
        public void setNaturalPerson(PersonType value) {
            this.naturalPerson = value;
        }

        /**
         * Gets the value of the legalPerson property.
         * 
         * @return
         *     possible object is
         *     {@link LegalPersonType }
         *     
         */
        public LegalPersonType getLegalPerson() {
            return legalPerson;
        }

        /**
         * Sets the value of the legalPerson property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalPersonType }
         *     
         */
        public void setLegalPerson(LegalPersonType value) {
            this.legalPerson = value;
        }

    }

}
