//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 05:27:25 PM CEST 
//


package sk.mirri.ootsevidencefinder.wsplugin.sdg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sk.mirri.oots.projectatonbe.wsplugin.sdg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InformationConcept_QNAME = new QName("http://data.europa.eu/p4s", "InformationConcept");
    private final static QName _Language_QNAME = new QName("http://data.europa.eu/p4s", "Language");
    private final static QName _EvidenceProvider_QNAME = new QName("http://data.europa.eu/p4s", "EvidenceProvider");
    private final static QName _AccessService_QNAME = new QName("http://data.europa.eu/p4s", "AccessService");
    private final static QName _Identifier_QNAME = new QName("http://data.europa.eu/p4s", "Identifier");
    private final static QName _Jurisdiction_QNAME = new QName("http://data.europa.eu/p4s", "Jurisdiction");
    private final static QName _ReferenceFramework_QNAME = new QName("http://data.europa.eu/p4s", "ReferenceFramework");
    private final static QName _DataServiceEvidenceType_QNAME = new QName("http://data.europa.eu/p4s", "DataServiceEvidenceType");
    private final static QName _Requirement_QNAME = new QName("http://data.europa.eu/p4s", "Requirement");
    private final static QName _Person_QNAME = new QName("http://data.europa.eu/p4s", "Person");
    private final static QName _Evidence_QNAME = new QName("http://data.europa.eu/p4s", "Evidence");
    private final static QName _Description_QNAME = new QName("http://data.europa.eu/p4s", "Description");
    private final static QName _EvidenceRequester_QNAME = new QName("http://data.europa.eu/p4s", "EvidenceRequester");
    private final static QName _EvidenceType_QNAME = new QName("http://data.europa.eu/p4s", "EvidenceType");
    private final static QName _EvidenceProviderClassification_QNAME = new QName("http://data.europa.eu/p4s", "EvidenceProviderClassification");
    private final static QName _Agent_QNAME = new QName("http://data.europa.eu/p4s", "Agent");
    private final static QName _Name_QNAME = new QName("http://data.europa.eu/p4s", "Name");
    private final static QName _EvidenceProviderJurisdictionDetermination_QNAME = new QName("http://data.europa.eu/p4s", "EvidenceProviderJurisdictionDetermination");
    private final static QName _LegalPerson_QNAME = new QName("http://data.europa.eu/p4s", "LegalPerson");
    private final static QName _ConformsTo_QNAME = new QName("http://data.europa.eu/p4s", "ConformsTo");
    private final static QName _EvidenceTypeList_QNAME = new QName("http://data.europa.eu/p4s", "EvidenceTypeList");
    private final static QName _Title_QNAME = new QName("http://data.europa.eu/p4s", "Title");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sk.mirri.oots.projectatonbe.wsplugin.sdg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EvidenceType }
     * 
     */
    public EvidenceType createEvidenceType() {
        return new EvidenceType();
    }

    /**
     * Create an instance of {@link EvidenceTypeType }
     * 
     */
    public EvidenceTypeType createEvidenceTypeType() {
        return new EvidenceTypeType();
    }

    /**
     * Create an instance of {@link InformationConceptType }
     * 
     */
    public InformationConceptType createInformationConceptType() {
        return new InformationConceptType();
    }

    /**
     * Create an instance of {@link AgentType }
     * 
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link MultilingualStringType }
     * 
     */
    public MultilingualStringType createMultilingualStringType() {
        return new MultilingualStringType();
    }

    /**
     * Create an instance of {@link LegalPersonType }
     * 
     */
    public LegalPersonType createLegalPersonType() {
        return new LegalPersonType();
    }

    /**
     * Create an instance of {@link EvidenceTypeListType }
     * 
     */
    public EvidenceTypeListType createEvidenceTypeListType() {
        return new EvidenceTypeListType();
    }

    /**
     * Create an instance of {@link JurisdictionDeterminationType }
     * 
     */
    public JurisdictionDeterminationType createJurisdictionDeterminationType() {
        return new JurisdictionDeterminationType();
    }

    /**
     * Create an instance of {@link JurisdictionType }
     * 
     */
    public JurisdictionType createJurisdictionType() {
        return new JurisdictionType();
    }

    /**
     * Create an instance of {@link ReferenceFrameworkType }
     * 
     */
    public ReferenceFrameworkType createReferenceFrameworkType() {
        return new ReferenceFrameworkType();
    }

    /**
     * Create an instance of {@link DataServiceEvidenceTypeType }
     * 
     */
    public DataServiceEvidenceTypeType createDataServiceEvidenceTypeType() {
        return new DataServiceEvidenceTypeType();
    }

    /**
     * Create an instance of {@link RequirementType }
     * 
     */
    public RequirementType createRequirementType() {
        return new RequirementType();
    }

    /**
     * Create an instance of {@link DataServiceType }
     * 
     */
    public DataServiceType createDataServiceType() {
        return new DataServiceType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link EvidenceTypeDistributionType }
     * 
     */
    public EvidenceTypeDistributionType createEvidenceTypeDistributionType() {
        return new EvidenceTypeDistributionType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link SupportedValueType }
     * 
     */
    public SupportedValueType createSupportedValueType() {
        return new SupportedValueType();
    }

    /**
     * Create an instance of {@link AttributeKeyValuePairType }
     * 
     */
    public AttributeKeyValuePairType createAttributeKeyValuePairType() {
        return new AttributeKeyValuePairType();
    }

    /**
     * Create an instance of {@link EvidenceProviderType }
     * 
     */
    public EvidenceProviderType createEvidenceProviderType() {
        return new EvidenceProviderType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link DistributionType }
     * 
     */
    public DistributionType createDistributionType() {
        return new DistributionType();
    }

    /**
     * Create an instance of {@link EvidenceType.IsAbout }
     * 
     */
    public EvidenceType.IsAbout createEvidenceTypeIsAbout() {
        return new EvidenceType.IsAbout();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationConceptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "InformationConcept")
    public JAXBElement<InformationConceptType> createInformationConcept(InformationConceptType value) {
        return new JAXBElement<InformationConceptType>(_InformationConcept_QNAME, InformationConceptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Language")
    public JAXBElement<CodeType> createLanguage(CodeType value) {
        return new JAXBElement<CodeType>(_Language_QNAME, CodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "EvidenceProvider")
    public JAXBElement<AgentType> createEvidenceProvider(AgentType value) {
        return new JAXBElement<AgentType>(_EvidenceProvider_QNAME, AgentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "AccessService")
    public JAXBElement<DataServiceType> createAccessService(DataServiceType value) {
        return new JAXBElement<DataServiceType>(_AccessService_QNAME, DataServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Identifier")
    public JAXBElement<IdentifierType> createIdentifier(IdentifierType value) {
        return new JAXBElement<IdentifierType>(_Identifier_QNAME, IdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Jurisdiction")
    public JAXBElement<JurisdictionType> createJurisdiction(JurisdictionType value) {
        return new JAXBElement<JurisdictionType>(_Jurisdiction_QNAME, JurisdictionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceFrameworkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "ReferenceFramework")
    public JAXBElement<ReferenceFrameworkType> createReferenceFramework(ReferenceFrameworkType value) {
        return new JAXBElement<ReferenceFrameworkType>(_ReferenceFramework_QNAME, ReferenceFrameworkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataServiceEvidenceTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "DataServiceEvidenceType")
    public JAXBElement<DataServiceEvidenceTypeType> createDataServiceEvidenceType(DataServiceEvidenceTypeType value) {
        return new JAXBElement<DataServiceEvidenceTypeType>(_DataServiceEvidenceType_QNAME, DataServiceEvidenceTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequirementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Requirement")
    public JAXBElement<RequirementType> createRequirement(RequirementType value) {
        return new JAXBElement<RequirementType>(_Requirement_QNAME, RequirementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EvidenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Evidence")
    public JAXBElement<EvidenceType> createEvidence(EvidenceType value) {
        return new JAXBElement<EvidenceType>(_Evidence_QNAME, EvidenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultilingualStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Description")
    public JAXBElement<MultilingualStringType> createDescription(MultilingualStringType value) {
        return new JAXBElement<MultilingualStringType>(_Description_QNAME, MultilingualStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "EvidenceRequester")
    public JAXBElement<AgentType> createEvidenceRequester(AgentType value) {
        return new JAXBElement<AgentType>(_EvidenceRequester_QNAME, AgentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EvidenceTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "EvidenceType")
    public JAXBElement<EvidenceTypeType> createEvidenceType(EvidenceTypeType value) {
        return new JAXBElement<EvidenceTypeType>(_EvidenceType_QNAME, EvidenceTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationConceptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "EvidenceProviderClassification")
    public JAXBElement<InformationConceptType> createEvidenceProviderClassification(InformationConceptType value) {
        return new JAXBElement<InformationConceptType>(_EvidenceProviderClassification_QNAME, InformationConceptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Agent")
    public JAXBElement<AgentType> createAgent(AgentType value) {
        return new JAXBElement<AgentType>(_Agent_QNAME, AgentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultilingualStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Name")
    public JAXBElement<MultilingualStringType> createName(MultilingualStringType value) {
        return new JAXBElement<MultilingualStringType>(_Name_QNAME, MultilingualStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionDeterminationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "EvidenceProviderJurisdictionDetermination")
    public JAXBElement<JurisdictionDeterminationType> createEvidenceProviderJurisdictionDetermination(JurisdictionDeterminationType value) {
        return new JAXBElement<JurisdictionDeterminationType>(_EvidenceProviderJurisdictionDetermination_QNAME, JurisdictionDeterminationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LegalPersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "LegalPerson")
    public JAXBElement<LegalPersonType> createLegalPerson(LegalPersonType value) {
        return new JAXBElement<LegalPersonType>(_LegalPerson_QNAME, LegalPersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "ConformsTo")
    public JAXBElement<String> createConformsTo(String value) {
        return new JAXBElement<String>(_ConformsTo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EvidenceTypeListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "EvidenceTypeList")
    public JAXBElement<EvidenceTypeListType> createEvidenceTypeList(EvidenceTypeListType value) {
        return new JAXBElement<EvidenceTypeListType>(_EvidenceTypeList_QNAME, EvidenceTypeListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultilingualStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://data.europa.eu/p4s", name = "Title")
    public JAXBElement<MultilingualStringType> createTitle(MultilingualStringType value) {
        return new JAXBElement<MultilingualStringType>(_Title_QNAME, MultilingualStringType.class, null, value);
    }

}
