//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 05:25:28 PM CEST 
//


package sk.mirri.ootspoc.wsplugin.regrep4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="mode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="CreateOrReplace"/>
 *     &lt;enumeration value="CreateOrVersion"/>
 *     &lt;enumeration value="CreateOnly"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "mode", namespace = "urn:oasis:names:tc:ebxml-regrep:xsd:lcm:4.0")
@XmlEnum
public enum Mode {

    @XmlEnumValue("CreateOrReplace")
    CREATE_OR_REPLACE("CreateOrReplace"),
    @XmlEnumValue("CreateOrVersion")
    CREATE_OR_VERSION("CreateOrVersion"),
    @XmlEnumValue("CreateOnly")
    CREATE_ONLY("CreateOnly");
    private final String value;

    Mode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Mode fromValue(String v) {
        for (Mode c: Mode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
