//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 05:27:25 PM CEST 
//


package sk.mirri.ootspoc.wsplugin.sdg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EvidenceTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EvidenceTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EvidenceTypeClassification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://data.europa.eu/p4s}Title" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://data.europa.eu/p4s}Description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://data.europa.eu/p4s}Jurisdiction" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Distribution" type="{http://data.europa.eu/p4s}DistributionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvidenceTypeType", propOrder = {
    "evidenceTypeClassification",
    "title",
    "description",
    "jurisdiction",
    "distribution"
})
public class EvidenceTypeType {

    @XmlElement(name = "EvidenceTypeClassification", required = true)
    protected String evidenceTypeClassification;
    @XmlElement(name = "Title", required = true)
    protected List<MultilingualStringType> title;
    @XmlElement(name = "Description")
    protected List<MultilingualStringType> description;
    @XmlElement(name = "Jurisdiction")
    protected List<JurisdictionType> jurisdiction;
    @XmlElement(name = "Distribution")
    protected List<DistributionType> distribution;

    /**
     * Gets the value of the evidenceTypeClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvidenceTypeClassification() {
        return evidenceTypeClassification;
    }

    /**
     * Sets the value of the evidenceTypeClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvidenceTypeClassification(String value) {
        this.evidenceTypeClassification = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultilingualStringType }
     * 
     * 
     */
    public List<MultilingualStringType> getTitle() {
        if (title == null) {
            title = new ArrayList<MultilingualStringType>();
        }
        return this.title;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultilingualStringType }
     * 
     * 
     */
    public List<MultilingualStringType> getDescription() {
        if (description == null) {
            description = new ArrayList<MultilingualStringType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jurisdiction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJurisdiction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JurisdictionType }
     * 
     * 
     */
    public List<JurisdictionType> getJurisdiction() {
        if (jurisdiction == null) {
            jurisdiction = new ArrayList<JurisdictionType>();
        }
        return this.jurisdiction;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistributionType }
     * 
     * 
     */
    public List<DistributionType> getDistribution() {
        if (distribution == null) {
            distribution = new ArrayList<DistributionType>();
        }
        return this.distribution;
    }

}
