//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.19 at 05:27:25 PM CEST 
//


package sk.mirri.ootspoc.wsplugin.sdg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JurisdictionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JurisdictionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AdminUnitLevel1" type="{http://data.europa.eu/p4s}CodeType"/>
 *         &lt;element name="AdminUnitLevel2" type="{http://data.europa.eu/p4s}CodeType" minOccurs="0"/>
 *         &lt;element name="AdminUnitLevel3" type="{http://data.europa.eu/p4s}CodeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JurisdictionType", propOrder = {
    "adminUnitLevel1",
    "adminUnitLevel2",
    "adminUnitLevel3"
})
public class JurisdictionType {

    @XmlElement(name = "AdminUnitLevel1", required = true)
    protected CodeType adminUnitLevel1;
    @XmlElement(name = "AdminUnitLevel2")
    protected CodeType adminUnitLevel2;
    @XmlElement(name = "AdminUnitLevel3")
    protected CodeType adminUnitLevel3;

    /**
     * Gets the value of the adminUnitLevel1 property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getAdminUnitLevel1() {
        return adminUnitLevel1;
    }

    /**
     * Sets the value of the adminUnitLevel1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setAdminUnitLevel1(CodeType value) {
        this.adminUnitLevel1 = value;
    }

    /**
     * Gets the value of the adminUnitLevel2 property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getAdminUnitLevel2() {
        return adminUnitLevel2;
    }

    /**
     * Sets the value of the adminUnitLevel2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setAdminUnitLevel2(CodeType value) {
        this.adminUnitLevel2 = value;
    }

    /**
     * Gets the value of the adminUnitLevel3 property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getAdminUnitLevel3() {
        return adminUnitLevel3;
    }

    /**
     * Sets the value of the adminUnitLevel3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setAdminUnitLevel3(CodeType value) {
        this.adminUnitLevel3 = value;
    }

}
